// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCFngZT75OvRe6arC2limXujdrRceEv68',
    appId: '1:33185060884:web:20e029815a1bdc0fd82f01',
    messagingSenderId: '33185060884',
    projectId: 'interfaces-43532',
    authDomain: 'interfaces-43532.firebaseapp.com',
    databaseURL: 'https://interfaces-43532-default-rtdb.firebaseio.com',
    storageBucket: 'interfaces-43532.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW7paw4sPIPDIA044mxUQsGBw9mtNVdgA',
    appId: '1:33185060884:android:92461a1cb051d106d82f01',
    messagingSenderId: '33185060884',
    projectId: 'interfaces-43532',
    databaseURL: 'https://interfaces-43532-default-rtdb.firebaseio.com',
    storageBucket: 'interfaces-43532.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6sr_L_XeQqHa1dZBzahSDYqY3gGdXAuQ',
    appId: '1:33185060884:ios:b507737e4cd73cb9d82f01',
    messagingSenderId: '33185060884',
    projectId: 'interfaces-43532',
    databaseURL: 'https://interfaces-43532-default-rtdb.firebaseio.com',
    storageBucket: 'interfaces-43532.appspot.com',
    iosClientId: '33185060884-aau4k2p6dvh4lm3eo3bqln7bmcenos5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelAgencyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6sr_L_XeQqHa1dZBzahSDYqY3gGdXAuQ',
    appId: '1:33185060884:ios:b507737e4cd73cb9d82f01',
    messagingSenderId: '33185060884',
    projectId: 'interfaces-43532',
    databaseURL: 'https://interfaces-43532-default-rtdb.firebaseio.com',
    storageBucket: 'interfaces-43532.appspot.com',
    iosClientId: '33185060884-aau4k2p6dvh4lm3eo3bqln7bmcenos5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelAgencyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCFngZT75OvRe6arC2limXujdrRceEv68',
    appId: '1:33185060884:web:22de27fc16786cf2d82f01',
    messagingSenderId: '33185060884',
    projectId: 'interfaces-43532',
    authDomain: 'interfaces-43532.firebaseapp.com',
    databaseURL: 'https://interfaces-43532-default-rtdb.firebaseio.com',
    storageBucket: 'interfaces-43532.appspot.com',
  );
}
